
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpdwavxxcdxmailizusm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZHdhdnh4Y2R4bWFpbGl6dXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzY5MzQsImV4cCI6MjA2MTY1MjkzNH0.CqXqS-I7aFx-7HcHAD6ioeWdiuub7flRfk6Y3ftnFdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
